### ISSUE TITLE
Page fails to save

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#847] opened 2022-06-23 00:01 UTC
This page is failing to save. it doesn't look like its a readability issue, but something with fetching/parsing fetched content.

https://www.hankyung.com/economy/article/2022062292911

**Comment by sywhb** [comment] 2022-06-28 14:07
@jacksonh i'm still trying to figure out the cause of issue. It's weird that sometimes it works but sometimes it does not

**Comment by sywhb** [comment] 2022-11-25 09:20
Close this one as it is fixed now

**Closed by sywhb** 2022-11-25 09:20 UTC
Labels: API, readability

**Comment by jacksonh** [comment] 2022-11-25 09:24
Nice, thanks for cleaning up
