### ISSUE TITLE
Feature Request : Unable to add lables when sharing from browser in Andriod.

### ISSUE THREAD

**Issue by dipeshsingh253** [omnivore-app/omnivore#3697] opened 2024-03-19 10:26 UTC
When sharing links from the Android browser to save them in Omnivore, I don't get a screen or option to add labels to that URL, as a result, I have to go to the Omnivore app to add labels.

https://github.com/omnivore-app/omnivore/assets/84814627/f887e520-0552-4bd4-898c-67983c3da71b

As in the video above, you can see it is directly saved in Omnivore without any prompt for adding labels.

Loved your work, thanks for developing Omnivore.

**Comment by camgraff** [comment] 2024-04-28 21:42
+1 pocket has this feature, it would be a great addition to omnivore

**Comment by Phlogi** [comment] 2024-05-22 14:51
duplicate of #2230

**Closed** 2024-11-18 10:35 UTC
Labels: android
