### ISSUE TITLE
Login on Android app not working

### ISSUE THREAD

**Issue by domsch1988** [omnivore-app/omnivore#2182] opened 2023-05-10 20:17 UTC
I just set up omnivore. Login on the PWA through chrome works, but filling the same login from bitwarden tells me my login is wrong.
This is on a Pixel 7, Android 13, Omnivore installed from Playstore.
I also tried resetting my Password already.

**Comment by jacksonh** [comment] 2023-05-11 00:51
Thanks Dom, do you mind emailing me the email address you are using to login at jacksonh@omnivore.app -- I have a feeling it's a formatting thing like a space after the address not being removed.

**Comment by domsch1988** [comment] 2023-05-11 04:04
Thanks for looking into this. Mail is send.

**Comment by jacksonh** [comment] 2023-05-11 04:17
Going to close this issue as I think it has been resolved, duplicate of https://github.com/omnivore-app/omnivore/issues/2166

**Closed by jacksonh** 2023-05-11 04:17 UTC

**Comment by domsch1988** [comment] 2023-05-11 04:21
Yes, works fine now. Thank you
