### ISSUE TITLE
Improve support for users that want to deploy their own backened

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#25] opened 2022-02-12 17:56 UTC
Currently Omnivore relies on a few GCP services to run, but open source users will likely want to deploy the api, web, and content fetching (puppeteer-parse) service to another platform. We need to come up with a list of target platforms and supported deployment configurations that are realistic for users wanting to deploy a minimalistic configuration.

Some of the services we currently rely on:

- [ ] Pubsub & Cloud Task -- task manager is used for schedule jobs such as content fetching
- [ ] CloudStorage -- we use CloudStorage as our main blob storage for PDF files
- [ ] Cloud Functions -- we deploy the pupeteer-parse service to a google cloud function

Other services we are using:

- [ ] SendGrid Inbound Parse -- to receive income email and invoke a webhook (running on a GCP Cloud Function)

**Comment by Limezy** [comment] 2022-04-27 05:03
Hi, thanks for trying to make Omnivore self-hostable !
For the CloudStorage part, could it be replaced by a MinIO instance with minor modifications on your side ?
For the SendGrid I guess a simple SMTP connector would be sufficient ?
For the auth process, if you make your app compatible with passport.js would be very easy for the community to then add connectors as per their needs. I would recommand OIDC as the primary choice.

**Comment by menelic** [comment] 2022-07-15 20:46
Thanks for a great tool - making this a nextcloud app would make this easy to deploy for many non technical users who have access to nextcloud instances. The app fits well with the open nextcloud ecossystem and meet a need not adressed by any nextcoud app.

**Comment by Nevarro** [comment] 2023-05-01 10:33
Could we get a progress update? Omnivore is exactly what I am looking for – only production-level self-hosting is missing.

**Comment by Coo-ops** [comment] 2023-05-09 00:54
Please update to fully open source. Thank you.

**Comment by jacksonh** [comment] 2023-05-09 00:56
> Please update to fully open source. Thank you.

Hi @Coo-ops the only piece that isn't open source is a PDF viewer library that we license, in the future we will try to replace this with pdf.js.

**Comment by obvionaoe** [comment] 2023-09-27 17:59
any new progress on this issue?

**Comment by r0bbie** [comment] 2023-11-18 21:05
I really want to go all-in on Omnivore. Coming across from Wallabag (and tried out a load of other options) the UX seems great, and happy to see it be open source! So been keeping an eye on this - right now both the lack of ability to self-host (or at least do so easily!) paired with the lack of any data export function (locking you in) makes me really hesitant..

If data export existed I'd at least be more willing to go with your hosted version for now, knowing it'll either be easy to migrate over when self-hosting is properly available (or to migrate my data to another solution altogether in the event self-hosting failed to materialise).

Wondered if there are any updates on this at present?

**Comment by stanthewizzard** [comment] 2023-11-23 17:37
deployment with docker won't do the trick ?
I want omnivore in house

**Comment by jerryzhang721** [comment] 2023-11-27 12:30
Is there a detailed tutorial for docker self-hosting?

**Comment by r0bbie** [comment] 2023-11-27 15:45
@jerryzhang721 All I've been able to find are the extremely basic instructions in the readme (https://github.com/omnivore-app/omnivore#how-to-setup-local-development-computer), but I was simply unable to get this working when using a custom domain rather than local IP/port. And I'm still extremely unclear on if all the external cloud dependencies have been refactored out yet allowing proper self-hosting or not..

**Comment by axelson** [comment] 2023-12-01 17:23
I'm very much hoping to self-host Omnivore as well!

I didn't see these docs posted in this issue so I'll post them here:
- The official self-hosting docs: https://docs.omnivore.app/self-hosting/self-hosting.html
- Those docs just point you to this blog post from earlier this year (which is fairly detailed but uses fly.io) https://blog.omnivore.app/p/deploying-a-minimal-self-hosted-omnivore

**Comment by grapemix** [comment] 2023-12-05 23:51
For the record, @lawrencegripper did contribute on k8s setup in https://github.com/omnivore-app/omnivore/pull/2966. Unfortunately, it is in WIP and he is unavailable.

**Comment by se-jaeger** [comment] 2023-12-06 08:45
> For the record, @lawrencegripper did contribute on k8s setup in #2966. Unfortunately, it is in WIP and he is unavailable.

Thanks for this pointer! I'm currently thinking about/planning to work on a Helm chart. Will probably start over the Christmas days. 

Feel free to ping me or connect if you plan to support.

**Comment by grapemix** [comment] 2023-12-13 20:01
> > For the record, @lawrencegripper did contribute on k8s setup in #2966. Unfortunately, it is in WIP and he is unavailable.
> 
> Thanks for this pointer! I'm currently thinking about/planning to work on a Helm chart. Will probably start over the Christmas days.
> 
> Feel free to ping me or connect if you would like to support.

FYI, not sure if you heard about https://bjw-s.github.io/helm-charts/docs/app-template/, it is pretty popular and it probably can save you quite a lot of time in this case. Also, lots of helm users already have deployed cloudnative-pg or something equivalent, script to bootstrap PG is likely not needed.

**Comment by se-jaeger** [comment] 2024-01-07 14:00
> > For the record, @lawrencegripper did contribute on k8s setup in #2966. Unfortunately, it is in WIP and he is unavailable.
> 
> Thanks for this pointer! I'm currently thinking about/planning to work on a Helm chart. Will probably start over the Christmas days.
> 
> Feel free to ping me or connect if you would like to support.

Hi, sorry for the late response there were some hurdles I had to overcome.

As @grapemix suggested, I use the [bjw-s helm chart](https://bjw-s.github.io/helm-charts/docs/app-template/) to setup a functioning instance (Web, API, content-fetch). You can found the current (WIP) version here: https://github.com/se-jaeger/omnivore

There are some things I want to improve but would love to get feedback in the meantime:
- documentation
- health checks
- RSS 

One more remark. I built and pushed the images to my Docker Hub account: https://hub.docker.com/u/sejaeger Working on #3177 would definitively improve the chart.

**Comment by se-jaeger** [comment] 2024-01-18 07:37
FYI: already merged #3385

**Comment by Nevarro** [comment] 2024-01-23 21:13
Any news on docker self-hosting?

**Comment by mbhkoay** [comment] 2024-02-04 02:45
Sharing my experience attempting to self-host this, not a coder at all so trying to fix some things is out of my expertise. 
I self-host stuff on my unraid machine, so your mileage may vary. 

1. Git clone
`git clone https://github.com/omnivore-app/omnivore`

2. Change directory 
`cd omnivore`

3. Adjust docker-compose
a. added lines to create docker custom network.
b. replace all secrets and environments required. Refer docker compose file. 
c. I think I messed some things up while updating the postgres password, so I ended up not changing them. 

4. Reverse proxy for port 3000 & 4000 (or the changed port number)
5. Start docker
`docker compose up --detach`

6. Outstanding items & observations
a. Readme says **to save pages** puppeteer-parse  is required outside of docker - Not sure if this can be dockerised
b. by default the login is demo@omnivore.app, password: demo_password. Have not found any settings to change password from within the app. I guess you can click forget password and reset it via email, but I haven't tried and think that it is likely that it won't work. 
c. No way to disable the signup button yet
d. content-fetch is not working, it throws an error about redisURL not supplied. Attempted to throw in a redis container to see if it works. Apparently not. You can see the additional section in the docker compose. 
e. se-jaeger's contribution using helm chart is something that I have yet to explore. (No experience at all with helm/Kubernetes etc.) He mentions the requirement of elastic-search, as well as an alternative to handle RSS Subscriptions. 

```
version: '3'
services:
  postgres:
    image: "ankane/pgvector:v0.5.1"
    container_name: "omnivore-postgres"
    environment:
      - POSTGRES_USER=postgres #nochange?
      - POSTGRES_PASSWORD=postgres #nochange?
      - POSTGRES_DB=omnivore
      - PG_POOL_MAX=20
    healthcheck:
      test: "exit 0"
      interval: 2s
      timeout: 12s
      retries: 3
    expose:
      - 5432 #change-likely-not-required from 5432
    networks: #custom docker network
      - omnivore #custom docker network

  migrate:
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    container_name: "omnivore-migrate"
    command: '/bin/sh ./packages/db/setup.sh' # Also create a demo user with email: demo@omnivore.app, password: demo_password
    environment:
      - PGPASSWORD=postgres #nochange?
      - POSTGRES_USER=postgres #nochange?
      - PG_HOST=postgres
      - PG_PASSWORD=app_pass #changeme-postgres-app-pass
      - PG_DB=omnivore
    depends_on:
      postgres:
        condition: service_healthy
    networks: #custom docker network
      - omnivore #custom docker network

  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    container_name: "omnivore-api"
    ports:
      - "4000:8080"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 0.0.0.0 8080 || exit 1"]
      interval: 15s
      timeout: 90s
    environment:
      - API_ENV=local
      - PG_HOST=postgres
      - PG_USER=app_user #changeme-postgres-app-user
      - PG_PASSWORD=app_pass #changeme-postgres-app-pass
      - PG_DB=omnivore
      - PG_PORT=5432 #change-likely-not-required from 5432
      - PG_POOL_MAX=20
      - JAEGER_HOST=jaeger
      - IMAGE_PROXY_SECRET=aaaaaaaaaaaaaaaaaaa #changeme
      - JWT_SECRET=bbbbbbbbbbbbbbbbbbbbbbbbbbb #changemejwt
      - SSO_JWT_SECRET=ccccccccccccccccccccccc #changeme
      - CLIENT_URL=https://omnivore.some.domain #change-port-3000-if-required
      - GATEWAY_URL=https://api.omnivore.some.domain/api #not sure if need to change? originally http://localhost:8080/api
      - CONTENT_FETCH_URL=http://content-fetch:8080/?token=dddddddddddddddddddddddd #changemetoken
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks: #custom docker network
      - omnivore #custom docker network

  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
      args:
        - APP_ENV=prod
        - BASE_URL=https://omnivore.some.domain #changeme-domain-url e.g. https://omnivore.domain.com
        - SERVER_BASE_URL=https://api.omnivore.some.domain #changeme-api-server-domain-url e.g. https://api.omnivore.domain.com
        - HIGHLIGHTS_BASE_URL=https://omnivore.some.domain #changeme-domain-url e.g. https://omnivore.domain.com
    container_name: "omnivore-web"
    ports:
      - "3001:8080" #change-port-3000-if-required
    environment:
      - NEXT_PUBLIC_APP_ENV=prod
      - NEXT_PUBLIC_BASE_URL=https://omnivore.some.domain #changeme-domain-url e.g. https://omnivore.domain.com
      - NEXT_PUBLIC_SERVER_BASE_URL=https://api.omnivore.some.domain #changeme-api-server-domain-url e.g. https://api.omnivore.domain.com
      - NEXT_PUBLIC_HIGHLIGHTS_BASE_URL=https://omnivore.some.domain #changeme-domain-url e.g. https://omnivore.domain.com
    depends_on:
      api:
        condition: service_healthy
    networks: #custom docker network
      - omnivore #custom docker network

  content-fetch:
    build:
      context: .
      dockerfile: ./packages/content-fetch/Dockerfile
    container_name: "omnivore-content-fetch"
    ports:
      - "9090:8080"
    environment:
      - JWT_SECRET=bbbbbbbbbbbbbbbbbbbbbbbbbbb #changemejwt
      - VERIFICATION_TOKEN=dddddddddddddddddddddddd #changemetoken
      - REST_BACKEND_ENDPOINT=https://api.omnivore.some.domain/api #not sure if need to change? originally http://api:8080/api
#      - REDISURL=redis://omnivore-redis:6379 #redis
    depends_on:
      api:
        condition: service_healthy
    networks: #custom docker network
      - omnivore #custom docker network

#################   redis   ###############
#  omnivore-redis:
#    image: redis:latest
#    container_name: omnivore-redis
#    environment:
#      - TZ=Asia/Kuala_Lumpur
#    restart: always
#    networks:
#      - omnivore
#################   redis   ###############

networks: #custom docker network
  omnivore: #custom docker network
```

**Comment by se-jaeger** [comment] 2024-02-04 06:54
Hi @mbhkoay,

thanks for this write up! Here are some pointers that may help.

> 3.c. I think I messed some things up while updating the postgres password, so I ended up not changing them.

In the [https://github.com/omnivore-app/omnivore/blob/main/self-hosting/helm/values.yaml](values.yaml) file, I added some hard coded credentials (`PG_DB`, `PG_USER`) that are also hard coded in the code base, which is why can't change them easily.

> 6.b. by default the login is demo@omnivore.app, password: demo_password.

I added a environment variable that allows to turn-off the creation of this default user: `NO_DEMO_USER=1`. However, if you register a new one, make sure to follow the steps documented [here](https://blog.omnivore.app/i/120191967/verifying-your-new-account-email) to verify it. (Normally, you would get an email that asks to click a link)

> 6.d. content-fetch is not working, it throws an error about redisURL not supplied. Attempted to throw in a redis container to see if it works. Apparently not. You can see the additional section in the docker compose.

Also stumbled across this. If you rollback to [this comment (e44616b01)](https://github.com/omnivore-app/omnivore/commit/e44616b01d863407b0e3fd33b7f990343e0f6139), which is the latest before redis is required for content-fetch, it should be possible to run it.

Hope, I'll find some time to dive into the Redis changes to propose a solution for self-hosting.

Hope it helps. Cheers.

**Comment by mariusrugan** [comment] 2024-02-14 09:41
Hi @mbhkoay and @se-jaeger,
thanks both for your contributions, 

is still unclear to me if elastic is needed.  
looking at the docker-compose from the projects' root, i just see pgvector (postgres+pgvector).

thanks in advance!

**Comment by jacksonh** [comment] 2024-02-14 09:44
Hey @mariusrugan we actually just dropped the elastic requirement recently, we're also in the middle of pulling out most of the GCP requirements and getting things down to two images (backend which will both process async jobs and run the API, and content-fetch which is the standalone service for fetching page content).

its in a bit of flux right now though as we wrap up this work.

**Comment by jacksonh** [comment] 2024-02-22 01:34
Docker images available here: https://github.com/orgs/omnivore-app/packages?repo_name=omnivore

**Comment by jacksonh** [comment] 2024-02-22 01:36
> > > For the record, @lawrencegripper did contribute on k8s setup in #2966. Unfortunately, it is in WIP and he is unavailable.
> > 
> > 
> > Thanks for this pointer! I'm currently thinking about/planning to work on a Helm chart. Will probably start over the Christmas days.
> > Feel free to ping me or connect if you would like to support.
> 
> Hi, sorry for the late response there were some hurdles I had to overcome.
> 
> As @grapemix suggested, I use the [bjw-s helm chart](https://bjw-s.github.io/helm-charts/docs/app-template/) to setup a functioning instance (Web, API, content-fetch). You can found the current (WIP) version here: https://github.com/se-jaeger/omnivore
> 
> There are some things I want to improve. However, in the meantime, I'd love to get feedback from you:
> 
> * documentation
> * health checks
> * RSS
> 
> One more remark. I built and pushed the images to my Docker Hub account: https://hub.docker.com/u/sejaeger Working on #3177 would definitively improve the chart.

I think a lot of this is improved with our move to bullmq jobs instead of cloud functions. The backend service has health checks for both the api server and the queue-processor server that also handle graceful shutdown via SIGTERM. We've started running both in k8s for our services as well.

**Comment by stanthewizzard** [comment] 2024-02-22 05:50
When using docker, is the extension for chrome able to connect to it ? Thanks

**Comment by jacksonh** [comment] 2024-02-22 05:51
You'd have to build the extension yourself. For security, the extension includes a content security policy that specifies the domains it can connect to.

**Comment by stanthewizzard** [comment] 2024-02-22 06:02
would be awesome to have settings for that to bypass default :)
thanks

**Comment by jacksonh** [comment] 2024-02-22 06:23
> would be awesome to have settings for that to bypass default :) thanks

I think from a security perspective its very unlikely we'd do this.

**Comment by stanthewizzard** [comment] 2024-02-22 06:40
To be quit honnest it's strange. I use wallabag and there are settings for selfhosted instance. Same for obsidian. and on and on :)

**Comment by jacksonh** [comment] 2024-02-22 06:43
OK thanks for your feedback

**Comment by sibbl** [comment] 2024-02-22 07:46
> I think from a security perspective its very unlikely we'd do this.

Could you please provide some insight into why this is not an option for this project?

Even the Bitwarden extension allows configuring a custom backend endpoint, and I would expect that password managers must adhere to higher security standards than this extension here.

It would be helpful for us to understand the reasoning behind this decision. I've been following this project very closely for a while and plan to use and support it, as soon as self-hosting is an easy and well supported option.

**Comment by mariusrugan** [comment] 2024-02-22 08:12
I second @sibbl , even more , Bitwarden official extension works with Vaultwarden backend (open source)

Also I've loosely explored Shiori, https://github.com/go-shiori/shiori-web-ext, which also has self-hosting capabilities ootb. 

I'm here for the iOS app/integration which i've researched and looks great but and i can load an unpacked & hacked extension in chrome, but it's not for the average person.

**Comment by jtsang4** [comment] 2024-02-22 11:37
> You'd have to build the extension yourself. For security, the extension includes a content security policy that specifies the domains it can connect to.

This project is under [AGPL-3.0 license](https://github.com/omnivore-app/omnivore#AGPL-3.0-1-ov-file), is it acceptable to modify source code then self-host it without publishing modified code?

In addition, if it is for long-term business interests consideration, I understand the impact caused by opening the backend endpoint. This project is excellent and requires a lot of work. I am willing to support using "custom backend endpoint" as a one-time purchase feature because opening features online does not affect that my personal data is still saved by myself.

I just looked at the donations on [OpenCollective](https://opencollective.com/omnivore) and felt that it was really not enough to encourage enthusiastic contributors, so I also donated $20 to the [Self-Hosting](https://opencollective.com/omnivore/projects/self-hosting) project.

**Comment by jacksonh** [comment] 2024-02-22 13:03
Sure, I'll create a project for this on OpenCollective. If funded will be happy to create a separate version of the extension without a content security policy.

**Comment by jacksonh** [comment] 2024-02-22 13:16
> , but it's not for the average person.

I suspect the average person should not be self hosting.

**Comment by jacksonh** [comment] 2024-02-22 13:18
OK, here you go. If we can fund this project we will create a separate version of the extension for people with self hosted backends: https://opencollective.com/omnivore/projects/extension-updates-for-self-hos

**Comment by mariusrugan** [comment] 2024-02-22 16:56
thanks for availability @jacksonh 

![Screenshot 2024-02-22 at 17 53 13](https://github.com/omnivore-app/omnivore/assets/143987/b3c0f960-8181-455f-9f84-708de97333dd)

i don't understand what would be the problem with the CSP. 
Can't be configurable ? It's a header.

**Comment by jacksonh** [comment] 2024-02-23 02:57
> i don't understand what would be the problem with the CSP. Can't be configurable ? It's a header.

The CSP is part of the extension manifest. If you look at bitwarden's CSP they just allow pretty much everything. I'm happy to create a separate version of the extension for self hosters but removing the CSP from the main extension seems like its sacrificing security for the majority (most users do not self host) for the convenience of the minority.

**Comment by r0bbie** [comment] 2024-02-23 09:58
Just to note on the discussion regarding the browser extension, the https://github.com/herrherrmann/omnivore-list-popup extension is really excellent, in my opinion the best Omnivore extension currently available in terms of functionality and UX, and that extension does allow an Omnivore instance to be set for compatibility with self-hosted installs (https://github.com/herrherrmann/omnivore-list-popup/issues/23).

Just as another option in case helpful for anyone while discussions regarding the official extension and self-hosting compatibility are ongoing :)

**Comment by mariusrugan** [comment] 2024-02-23 10:44
thanks a lot @r0bbie ! much appreciated !

**Comment by solidstudio** [comment] 2024-02-27 13:12
> Docker images available here: https://github.com/orgs/omnivore-app/packages?repo_name=omnivore

Anyone got a docker-compose file setup using the new images?

**Comment by grapemix** [comment] 2024-03-01 06:31
Thanks to [mbhkoay](https://github.com/mbhkoay)'s work. I give a try on deploying omnivore in my k8s + fluxcd cluster. 

Here is a few feedback:
1. web docker img is missing
2. the API pod has to be run as root. That's a security concern.
3. We have to append the VERIFICATION_TOKEN in CONTENT_FETCH_URL. That's not really k8s nor flux friendly. String concatenation is very hard on the k8s and flux side. String concatenation is much easier to be done in the server itself.
4. The liveness and readiness probes are not working. I used the common /v1/health path. I currently disable them.
5. Haven't tried the SSO_JWT_SECRET since web image is missing

I cannot fully test my deployment since the web img is missing. But I can see the api page.

Finally, thanks all for the hardwork. It is a good start.

**Comment by jacksonh** [comment] 2024-03-01 06:37
Thanks, this is what i use for our probes:

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_ah/health
            port: 8080
            scheme: HTTP
 ```
 
 regarding the web image currently you need to build it, because of the way next.js works you have to "bake" the environment variables like the API endpoint into the javascript bundle. There's some workarounds with replacing them in the docker image that I'd like to try but haven't had time yet.

**Comment by jacksonh** [comment] 2024-03-01 06:45
@grapemix can i ask how you are managing your secrets? Are you able to just store the entire CONTENT_FETCH_URL as a secret? Also i am wondering if we can remove that token in self hosted scenarios anyways.

**Comment by grapemix** [comment] 2024-03-02 08:41
1. @jacksonh, I am using external secret. I have to store the entire CONTENT_FETCH_URL as a secret entry, but this solution has two sources of truth for the VERIFICATION_TOKEN which increase the likelihood of operational mal-configuration.

**Comment by mariusrugan** [comment] 2024-03-10 15:58
i've deployed the latest chart with up-to-date values however i'm missing some ENV vars i think.

I have an error in the browser - frontend trying to reach: "api.omnivore.home.server"

```
CLIENT_URL: https://omnivore.example.com
GATEWAY_URL:  https://omnivore.example.com/api
 ```             
 
 anyone can help ?
 cc @se-jaeger 
 thanks in advance !
 
 ```
 6647-f41dd3ae553a9e89.js:1 
 POST https://api.omnivore.home.server/api/graphql net::ERR_NAME_NOT_RESOLVED
 ```

**Comment by philipp-koch** [comment] 2024-04-13 23:24
I think it would be a fantastic possibility for user to have their own Omnivore instance on their hardware running, thus controlling their own data! I run a small number of services in docker containers on my Synology NAS, and I'm sure that this is quite a common way for people like me who don't know enough how (or simply don't want to) to run a fully fledged web server to self-host stuff. 

If a way (and how-tp steps for getting it set up) to accomplish running Omnivore (front and backend) in docker containers, would there be a **way to export / migrate my existing data** (which right now is on https://Omnivore.app) **to the new instance**?

If I could run the backend myself, I'd gladly [support the creation of the "self-hosting-capable extension variant" financially](https://github.com/omnivore-app/omnivore/issues/25#issuecomment-1959440009).

**Comment by domonnss** [comment] 2024-04-28 11:33
I have tried self hosting.But,to be honestly,it's not easy to be deployed on my VM.I'll wait and try the updated deployment method.😥😥😥

**Comment by Mikilio** [comment] 2024-05-30 23:13
Regarding Cloud Storage: What is the currently envisioned solution? Has WebDAV been considered?

**Comment by maa-x** [comment] 2024-07-04 09:23
@Mikilio I've been working on making GCS optional, you can track progress [here](https://github.com/maa-x/omnivore/tree/add_fs_storage). 

If anyone is keen to help please let me know. This is rather outside my skillset so if you see anything looking a bit off do tell me.

**Comment by NonyLee** [comment] 2024-07-26 02:29
@Mikilio  [gcs-s3-adapter](https://github.com/NonyLee/gcs-s3-adapter) is a library to replace GCS.

Hope it helps.

**Comment by DDzwiedziu** [comment] 2024-10-07 11:52
I've just made a quick attempt at running in a LAN server, that hosts other services, with the provided Docker Compose file. And my quick spotlights are:
- port conflicts with existing services,
  - including internal services as Postgres and Redis,
- why use a PG replica? (or for who this DC file is meant?)
- not using variables for the host and ports,
- not using `.env` for passwords.

I'll make a next attempt with moving what I can to an `.env` file and restart later.

**Comment by Nevarro** [comment] 2024-10-29 18:23
At least, now it [becomes clear](https://blog.omnivore.app/p/omnivore-is-joining-elevenlabs), why there was no real effort towards making self-hosting easier.

**Comment by ClariNerd617** [comment] 2024-10-29 20:13
Well, so much for that. Guess we can always fork it and figure it out on our own, because I for one am not paying for Readwise Reader again.

**Comment by stanthewizzard** [comment] 2024-10-29 20:19
Linkwarden for a moment on my side

**Comment by mwnu** [comment] 2024-10-29 22:58
``

**Comment by thiswillbeyourgithub** [comment] 2024-10-31 03:32
> Linkwarden for a moment on my side

Does it support highlighting?

**Comment by fazzer4x** [comment] 2024-10-31 04:17
> > Linkwarden for a moment on my side
> 
> Does it support highlighting?

Try readeck! They just Adeles omnivore Import yesterday

**Comment by stanthewizzard** [comment] 2024-10-31 08:56
> > Linkwarden for a moment on my side
> 
> Does it support highlighting?

IDK
But very active

**Comment by stanthewizzard** [comment] 2024-10-31 08:57
> > > Linkwarden for a moment on my side
> > 
> > 
> > Does it support highlighting?
> 
> Try readeck! They just added omnivore Import yesterday

Deleted my docker last week for linkwarden
It was a good service

**Comment by asandikci** [comment] 2024-10-31 14:49
Linkwarden vs Readreck vs Wallabag?
Which one do you suggest? I need highlight feature

**Comment by asandikci** [comment] 2024-10-31 16:06
Why not wallabag?

**Comment by Limezy** [comment] 2024-10-31 16:29
I use wallabag since almost 10 years with success. Still a few pages not well scrapped but it works well. Didn't try the others though.

**Comment by philipp-koch** [comment] 2024-10-31 17:17
> Try readeck! They just added omnivore Import yesterday

I have also decided to switch to Readeck. It's a great piece of software — free, self-hosted, and “it just works”! It comes with browser extensions for Firefox and Chrome. And for those like me who want to self-host on their Synology NAS, [here's a really easy how-to](https://mariushosting.com/how-to-install-readeck-with-postgresql-on-your-synology-nas/).

I find it remarkable that Readeck's author [added an Omnivore import option](https://codeberg.org/readeck/readeck/issues/247) in just one day! 🤯 You can use said import functionality by clicking the “three dots”-button next to the “add new link” bar and choose “import bookmarks”:
![grafik](https://github.com/user-attachments/assets/246db0b3-228c-45a2-8184-6c692d901cc6)

You can then choose Omnivore import:
![grafik](https://github.com/user-attachments/assets/648d275f-b5aa-4c6d-90bc-0effcc170b7f)

You need an API key (which can be added via [Omnivore settings > API keys](https://omnivore.app/settings/api)). The process worked flawlessly for me and imported all my content, including all tags, without any errors whatsoever. 

Overall, highly recommended!

**Comment by nicoska84** [comment] 2024-10-31 17:35
> > Try readeck! They just added omnivore Import yesterday
> 
> 
> 
> I have also decided to switch to Readeck. It's a great piece of software — free, self-hosted, and “it just works”! It comes with browser extensions for Firefox and Chrome. And for those like me who want to self-host on their Synology NAS, [here's a really easy how-to](https://mariushosting.com/how-to-install-readeck-with-postgresql-on-your-synology-nas/).
> 
> 
> 
> I find it remarkable that Readeck's author [added an Omnivore import option](https://codeberg.org/readeck/readeck/issues/247) in just one day! 🤯 You can use said import functionality by clicking the “three dots”-button next to the “add new link” bar and choose “import bookmarks”:
> 
> ![grafik](https://github.com/user-attachments/assets/246db0b3-228c-45a2-8184-6c692d901cc6)
> 
> 
> 
> You can then choose Omnivore import:
> 
> ![grafik](https://github.com/user-attachments/assets/648d275f-b5aa-4c6d-90bc-0effcc170b7f)
> 
> 
> 
> You need an API key (which can be added via [Omnivore settings > API keys](https://omnivore.app/settings/api)). The process worked flawlessly for me and imported all my content, including all tags, without any errors whatsoever. 
> 
> 
> 
> Overall, highly recommended!

Do you know if there is a way to save from iPhone? Maybe a shortcut?
I could give a try

**Comment by philipp-koch** [comment] 2024-10-31 18:07
> Do you know if there is a way to save from iPhone? Maybe a shortcut?
> I could give a try

I'm not an Apple user. As far as I know, there's no dedicated mobile app (neither for Android nor iPhone), but Readeck itself is a mobile friendly web app, and as I said, there are extensions for Firefox and Chrome, which are usable from the iPhone as well, right? So, you could just do that: Use the browser extension or the web app itself, or install it as PWA.

**Comment by fazzer4x** [comment] 2024-10-31 18:12
There is at https://shareshortcuts.com/download/2696-send-page-to-readeck.html

**Comment by Mikilio** [comment] 2024-11-02 10:27
I am subscribed to this issue to receive news on the state of the actual issue in the title.
I would like people who want to suggest alternatives to Omnivore because of the current controversy to stick to express their frustrations in the respective issues for that.

For anyone looking to self-host Omnivore: At the moment, the PR #4465 looks promising and would close this issue.

**Closed** 2024-11-18 10:35 UTC

**Comment by Mikilio** [comment] 2024-11-19 13:38
bump

**Comment by Limezy** [comment] 2024-11-19 13:53
You should forget about Omnivore, I guess the linear bot gave us a clear answer on how much the new owner cares about self hosting. Did you have a look at Wallabag ?

**Comment by maa-x** [comment] 2024-11-19 14:54
Seems like a shame to dump it when I've got it running self-hosted. There's a PR which improves that (though I have yet to test it). 

It might be smart however to fork the repo for good?

**Comment by driversti** [comment] 2024-11-19 15:16
Hey folks. Have you read the article on their blog? Omnivore is shutting down at the end of November.

**Comment by thiswillbeyourgithub** [comment] 2024-11-19 16:00
There does not seem to be alternative that allow both webpage AND pdfs and highlighting. And even then, I think most import features of the other service don't include pdfs or highlights.

I think I could get buy just fine for a lot of years if I could just docker compose up an omnivore instance. But this is not yet doable right?

**Comment by adlpz** [comment] 2024-11-19 16:12
@maa-x I agree it'd be a shame to have all the work done in the last few weeks be wasted. A fork that the community can get behind would be best.

I have no clue however how such a migration could be organized. Maybe someone more experienced in open source governance could help.

@thiswillbeyourgithub I have just downloaded @Podginator's PR branch (#4465), built the images and self-hosted it. Appears to work as expected, I haven't done much behind navigating around, manually adding some links and doing some highlights though.

But surely appears to be something within reach.

**Comment by thiswillbeyourgithub** [comment] 2024-11-19 16:34
> @thiswillbeyourgithub I have just downloaded @Podginator's PR branch (https://github.com/omnivore-app/omnivore/pull/4465), built the images and self-hosted it. Appears to work as expected, I haven't done much behind navigating around, manually adding some links and doing some highlights though.
> But surely appears to be something within reach.

Great to hear. Thanks.

I know I would be open to paying a monthly donation to anyone who's improving a "main" fork. I'm sure I'm not the only one. That could incite forkers to join efforts.

**Comment by nileshtrivedi** [comment] 2024-11-20 10:22
> There does not seem to be alternative that allow both webpage AND pdfs and highlighting.

Doesn't [Zotero](https://www.zotero.org/) do that? It even has free sync storage of 300MB.

**Comment by thiswillbeyourgithub** [comment] 2024-11-20 11:19
> > There does not seem to be alternative that allow both webpage AND pdfs and highlighting.
> 
> Doesn't [Zotero](https://www.zotero.org/) do that? It even has free sync storage of 300MB.

Thanks a lot I had not considered using zotero. I thought it allowed highlighting pdf but not webpage, has that changed?

What I'm after is saving pdfs, webpages (and ideally .docx etc but I can manage), then reading, highlighting them, and accessing my highlights. Mobile support for all that too.

Can zotero do all that?

**Comment by thiswillbeyourgithub** [comment] 2024-11-20 12:35
> Except for mobile support, Zotero gives you everything you're looking for. They recently released v7 which brought support for webpage annotations. They also have an android app in alpha, which you can either build yourself or get a [nightly build from here](https://github.com/northword/zotero-android-nightly-build).

Very tempting. Thanks a lot!! I'll take a look someday

**Comment by menelic** [comment] 2024-11-21 12:21
@thiswillbeyourgithub @thelazyoxymoron zotero actually has a mobile app for iOS and Android that fully synchronizes with the desktop and web app. It has been in closed beta for a year, is well designed and fully functional. 

It is possible to highlight and annotate archived webpages. The only feature still lacking on the mobile app is freehand annotations in html - they do work great on pdf though, to the point tat recent color eInk tablets sch as the boox series of devices allow for a great, cross device workflow that truly matches and surpasses paper when it comes to syncing, searching sharing, backup etc.

The reason why I don't want to use zotero for read it later of web content is because I use it as a citation manager for my own and shared projects, so I dont want my library in zotero to contain thousands of articles I will never cite.

**Comment by thiswillbeyourgithub** [comment] 2024-11-21 12:37
Thanks a lot it's very helpful.

> The only feature still lacking on the mobile app is freehand annotations in html

Can you just tell me if we can annotate webpages using the webapp on mobile?

**Comment by auspiciouslink** [comment] 2024-11-30 00:49
@menelic, how can someone get in on this closed beta? I've been trying to cobble together SingleFile, syncthing, and KOReader just to be able to fill in for what I did with Omnivore on my Boox, but it's all super clumsy. Zotero already integrates fine with my PKM (Logseq), so this would be huge for me.

**Comment by thiswillbeyourgithub** [comment] 2024-12-05 15:05
> Can you just tell me if we can annotate webpages using the webapp on mobile?

I finally checked and no, the webpage highlighting is not yet supported.

> I appear to have 1.0.0-119 downloaded from the Aurora Store, but I can't do basic things like highlight in articles, even though I've seen screenshots where other people are doing it fine, so it makes me think not "officially" being in the beta might somehow mean I've ended up with some wrong version?

This one can highlight pdf fine : https://github.com/zotero/zotero-android/

There's also that one : https://github.com/northword/zotero-android-nightly-build

Obtainium makes it easy to get them updated.

**Comment by grapemix** [comment] 2024-12-07 01:51
For someone who are desperate for open source self hosted solution like omnivore: 

https://github.com/hoarder-app/hoarder
https://readeck.org/en/

PS: I don't have any relationship nor affiliated w/ them. I also won't guarantee their apps' quality. I do however will likely self host them in the near future.

**Comment by auspiciouslink** [comment] 2024-12-08 01:35
@thiswillbeyourgithub Thanks so much for checking!

I already have a solution that works great for PDFs. It's web clippings I need to be able to annotate on mobile for my use case. That's what I'm trying to replace from Omnivore.

Does it seem like Zotero's even trying to get there? My understanding is that this is sort of an "off-label" thing for me to want Zotero to do, not its core functionality.

**Comment by thiswillbeyourgithub** [comment] 2024-12-08 18:07
> It's web clippings I need to be able to annotate on mobile for my use case. That's what I'm trying to replace from Omnivore.

Same here!

> Does it seem like Zotero's even trying to get there? My understanding is that this is sort of an "off-label" thing for me to want Zotero to do, not its core functionality.

Frankly I don't know but I want to believe. As time goes on I'll more and more rely on zotero for my research anyway so I try to move my eggs there. I might just do a script that turns webpages into pdf straight from my phone and edit them as is, I don't know.


I don't think I recall reading somewhere that annotating snapshots was planned though, and it would make sense.

**Comment by volker-fr** [comment] 2024-12-08 20:41
For a long time I used the PrinterFriendly extension to create PDFs of websites, that I then imported into Zotero. No automation here, but you could automate PDF creation through other tools.

I moved on to Reader for non-research. Supports also email (newsletters) & RSS. RSS is also not supported for Zotero.

**Comment by arran4** [comment] 2024-12-08 21:51
I will probably just create an imap mailbox and use that for the short reads.
