### ISSUE TITLE
Unable to read pdfs in webapp

### ISSUE THREAD

**Issue by LBrockmanK** [omnivore-app/omnivore#3025] opened 2023-10-26 13:43 UTC
I am unable to view any pdf using the webapp. I tested this on chrome, firefox, and edge. Chrome was tested on two different computers and on chrome web browser for android (tried both wifi and data to ensure there wasn't some issue with my network). In all cases 3 loading dots simply persist indefinitely.

I am able to view pdfs without issue in the android app.

**Comment by jacksonh** [comment] 2023-10-26 13:47
I suspect this is some browser security related. Do you mind taking a screenshot of the error, also if possible can you open the Developer tools (in Chrome you go View -> Developer -> Developer Tools) and look for any errors in the Console tab?

**Comment by sofianbello** [comment] 2023-10-26 15:18
> I suspect this is some browser security related. Do you mind taking a screenshot of the error, also if possible can you open the Developer tools (in Chrome you go View -> Developer -> Developer Tools) and look for any errors in the Console tab?

I don't think so, I'm having the same issue since 2-3 Hours. I was working on the webversion this 4 hours ago. The console doesn't show any errors.

**Comment by LBrockmanK** [comment] 2023-10-26 16:39
No errors present in console, there  is a warning "A form field element should have an id or name attribute" but that seems to originate from the inbox page, not the pdf / document page.
![Screenshot 2023-10-26 113604](https://github.com/omnivore-app/omnivore/assets/78050278/f6f917d0-7ddd-40af-8161-4ac6ef9e5e3a)

**Comment by jacksonh** [comment] 2023-10-27 02:39
hey thanks for following up, it looks like this was caused by a library update. I've reverted that change for now.

**Comment by jacksonh** [comment] 2023-10-27 03:02
Going to leave this open as I try to figure out why this happened (and why our alerts weren't triggered)

**Comment by jacksonh** [comment] 2023-11-01 04:47
Will close this one down now as I understand what happened and think we can prevent in the future.

**Closed by jacksonh** 2023-11-01 04:47 UTC
Labels: Web
