### ISSUE TITLE
Support RTL languages

### ISSUE THREAD

**Issue by tmr232** [omnivore-app/omnivore#2961] opened 2023-10-18 07:10 UTC
Omnivore currently supports LTR languages only, leading to problematic text rendering on RTL languages like Hebrew and Arabic.

Here's what the text (taken from [this article](https://idanlandau.com/2023/10/16/%D7%9E%D7%9F-%D7%94%D7%91%D7%92%D7%99%D7%93%D7%94-%D7%93%D7%A8%D7%9A-%D7%94%D7%A7%D7%95%D7%A0%D7%A1%D7%A4%D7%99%D7%A8%D7%A6%D7%99%D7%94-%D7%90%D7%9C-%D7%94%D7%94%D7%99%D7%93%D7%91%D7%A8%D7%95%D7%AA/)) currently looks like:

![image](https://github.com/omnivore-app/omnivore/assets/1386239/55d43cd3-d9c8-4474-ab71-6b5daaca33b7)

Here's what it looks like in the original article:

![image](https://github.com/omnivore-app/omnivore/assets/1386239/66713390-4228-436e-a9a3-8d74f4361156)

And here's what it looks like in Omnivore when I add `direction: rtl` to the CSS:

![image](https://github.com/omnivore-app/omnivore/assets/1386239/816707dd-f4e3-43bd-b09a-5247fbca2ba4)

Note specifically the placement of the question marks in the last line.

This is critical for readability of RTL languages.

**Comment by jacksonh** [comment] 2024-03-04 05:58
Going to close this one as a dupe of https://github.com/omnivore-app/omnivore/issues/3279 and add some extra info there.

**Closed by jacksonh** 2024-03-04 05:58 UTC
