### ISSUE TITLE
Bump node-gyp for local development

### ISSUE THREAD

**Issue by pythoninthegrass** [omnivore-app/omnivore#2640] opened 2023-08-10 19:51 UTC
Hi there.

When building the `docker-compose.yml` locally, it fails on the `api_builder` layer due to a deprecation [upstream in Python](https://github.com/nodejs/gyp-next/commit/d0504e6700ce48f44957a4d5891b142a60be946f) 3.11 raising:
```bash
ValueError: invalid mode: 'rU' while trying to load binding.gyp
```
Node's not my forte, so it's unclear where to bump the `"node-gyp": "^9.4.0",` dependency — although it seems the top-level `yarn.lock` via `package.json` would be the most likely spot (cf. https://github.com/omnivore-app/omnivore/blob/main/yarn.lock#L21123.)

Happy to test suggestions and open a PR after getting a working solution running.

**OS**: macOS 12.6.7 (21G651)
**Docker**: version 24.0.5, build ced0996

[node-gyp_traceback_api_builder.log](https://github.com/omnivore-app/omnivore/files/12316729/node-gyp_traceback_api_builder.log)

**Comment by pythoninthegrass** [comment] 2023-08-10 19:53
```bash
λ docker compose up
[+] Building 48.7s (17/35)
 => [api internal] load build definition from Dockerfile                                                           0.0s
 => => transferring dockerfile: 1.89kB                                                                             0.0s
 => [api internal] load .dockerignore                                                                              0.0s
 => => transferring context: 156B                                                                                  0.0s
 => [api internal] load metadata for docker.io/library/node:18.16-alpine                                           0.0s
 => [api internal] load build context                                                                              0.1s
 => => transferring context: 80.02kB                                                                               0.0s
 => [api builder  1/23] FROM docker.io/library/node:18.16-alpine                                                   0.0s
 => CACHED [api builder  2/23] WORKDIR /app                                                                        0.0s
 => CACHED [api builder  3/23] RUN apk add g++ make python3                                                        0.0s
 => CACHED [api builder  4/23] COPY package.json .                                                                 0.0s
 => CACHED [api builder  5/23] COPY yarn.lock .                                                                    0.0s
 => CACHED [api builder  6/23] COPY tsconfig.json .                                                                0.0s
 => CACHED [api builder  7/23] COPY .prettierrc .                                                                  0.0s
 => CACHED [api builder  8/23] COPY .eslintrc .                                                                    0.0s
 => CACHED [api builder  9/23] COPY /packages/readabilityjs/package.json ./packages/readabilityjs/package.json     0.0s
 => CACHED [api builder 10/23] COPY /packages/api/package.json ./packages/api/package.json                         0.0s
 => CACHED [api builder 11/23] COPY /packages/text-to-speech/package.json ./packages/text-to-speech/package.json   0.0s
 => CACHED [api builder 12/23] COPY /packages/content-handler/package.json ./packages/content-handler/package.jso  0.0s
 => ERROR [api builder 13/23] RUN yarn install --pure-lockfile                                                    48.6s
```

**Comment by LeetaoGoooo** [comment] 2023-08-13 04:59
to resolve this issue before they fix it, you can modify the Dockerfile. It seems that the problem is caused by a lower version of @npmcli/run-script

<img width="441" alt="image" src="https://github.com/omnivore-app/omnivore/assets/10162120/8d1aff18-15ad-4ee4-b8f7-92a1de79bcdd">

```dockerfile
RUN yarn upgrade @npmcli/run-script@6.0.2 # add this line
RUN yarn install --pure-lockfile
```

<img width="1238" alt="image" src="https://github.com/omnivore-app/omnivore/assets/10162120/94e8ed9e-8afd-49e2-aa85-2e7eabb4b283">

**Comment by pythoninthegrass** [comment] 2023-08-15 04:21
@LeetaoGoooo That definitely gets further when adding the `@npmcli/run-script@6.0.2` run command to `packages/api/Dockerfile` line 19.

Now getting a new error:
```
=> ERROR [api builder 21/24] RUN yarn workspace @omnivore/api build                                              12.4s
------
 > [api builder 21/24] RUN yarn workspace @omnivore/api build:
0.155 yarn workspace v1.22.19
0.299 yarn run v1.22.19
0.320 $ tsc && yarn copy-files
12.26
12.26 <--- Last few GCs --->
12.26
12.26 [38:0xffff947f12f0]    11628 ms: Mark-sweep (reduce) 985.3 (1006.1) -> 984.8 (1003.6) MB, 221.9 / 0.0 ms  (+ 1.5 ms in 3 steps since start of marking, biggest step 1.0 ms, walltime since start of marking 228 ms) (average mu = 0.274, current mu = 0.243) fi[38:0xffff947f12f0]    11638 ms: Scavenge 985.9 (1003.6) -> 985.2 (1006.6) MB, 6.6 / 0.0 ms  (average mu = 0.274, current mu = 0.243) allocation failure;
12.26
12.26
12.26 <--- JS stacktrace --->
12.26
12.26 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
12.30 Aborted
12.31 error Command failed with exit code 134.
12.31 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12.32 error Command failed.
12.32 Exit code: 134
12.32 Command: /usr/local/bin/node
12.32 Arguments: /opt/yarn-v1.22.19/lib/cli.js build
12.32 Directory: /app/packages/api
12.32 Output:
12.32
12.32 info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn workspace @omnivore/api build" did not complete successfully: exit code: 134
```

Looks like an OOM error on Docker's end, but that's quite a bit of RAM just to install dependencies 🧐 

Will uncap system resources to see if that helps...

**Comment by pythoninthegrass** [comment] 2023-08-15 04:40
Bumping specs from 2 to 6 GB RAM, CPU 200% to 600% got past OOM (more the former, but figured maybe could speed up ops with more clock cycles.)

But two steps forward:
```
=> [web builder  9/12] RUN yarn install --pure-lockfile                                                          45.1s
 => => # yarn install v1.22.19
 => => # [1/4] Resolving packages...
 => => # [2/4] Fetching packages...
 => [content-fetch  3/20] WORKDIR /app                                                                             0.0s
 => [content-fetch  4/20] COPY package.json .                                                                      0.0s
 => [content-fetch  5/20] COPY yarn.lock .                                                                         0.0s
 => [content-fetch  6/20] COPY tsconfig.json .                                                                     0.0s
 => [content-fetch  7/20] COPY .prettierrc .                                                                       0.0s
 => [content-fetch  8/20] COPY .eslintrc .                                                                         0.0s
 => [content-fetch  9/20] COPY /packages/readabilityjs/package.json ./packages/readabilityjs/package.json          0.0s
 => [content-fetch 10/20] COPY /packages/content-handler/package.json ./packages/content-handler/package.json      0.0s
 => [content-fetch 11/20] COPY /packages/puppeteer-parse/package.json ./packages/puppeteer-parse/package.json      0.0s
 => ERROR [content-fetch 12/20] RUN yarn install --pure-lockfile                                                  32.4s
------
 > [content-fetch 12/20] RUN yarn install --pure-lockfile:
0.221 yarn install v1.22.19
0.338 [1/4] Resolving packages...
0.609 [2/4] Fetching packages...
20.26 [3/4] Linking dependencies...
20.26 warning "workspace-aggregator-9d3612f1-ad4b-4b1a-8243-aed35306aa5f > @omnivore/puppeteer-parse > puppeteer-extra-plugin-adblocker > @cliqz/adblocker-puppeteer@1.23.8" has unmet peer dependency "puppeteer@>5".
20.29 warning Workspaces can only be enabled in private projects.
27.89 [4/4] Building fresh packages...
30.61 error /app/node_modules/microtime: Command failed.
30.61 Exit code: 1
30.61 Command: node-gyp-build
30.61 Arguments:
30.61 Directory: /app/node_modules/microtime
30.61 Output:
30.61 gyp info it worked if it ends with ok
30.61 gyp info using node-gyp@7.1.2
30.61 gyp info using node@18.16.1 | linux | arm64
30.61 gyp info find Python using Python version 3.11.4 found at "/usr/bin/python3"
30.61 gyp http GET https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz
30.61 gyp http 200 https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz
30.61 gyp http GET https://nodejs.org/download/release/v18.16.1/SHASUMS256.txt
30.61 gyp http 200 https://nodejs.org/download/release/v18.16.1/SHASUMS256.txt
30.61 (node:41) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
30.61 (Use `node --trace-deprecation ...` to show where the warning was created)
30.61 gyp info spawn /usr/bin/python3
30.61 gyp info spawn args [
30.61 gyp info spawn args   '/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
30.61 gyp info spawn args   'binding.gyp',
30.61 gyp info spawn args   '-f',
30.61 gyp info spawn args   'make',
30.61 gyp info spawn args   '-I',
30.61 gyp info spawn args   '/app/node_modules/microtime/build/config.gypi',
30.61 gyp info spawn args   '-I',
30.61 gyp info spawn args   '/app/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
30.61 gyp info spawn args   '-I',
30.61 gyp info spawn args   '/root/.cache/node-gyp/18.16.1/include/node/common.gypi',
30.61 gyp info spawn args   '-Dlibrary=shared_library',
30.61 gyp info spawn args   '-Dvisibility=default',
30.61 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.16.1',
30.61 gyp info spawn args   '-Dnode_gyp_dir=/app/node_modules/@npmcli/run-script/node_modules/node-gyp',
30.61 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',
30.61 gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/microtime',
30.61 gyp info spawn args   '-Dnode_engine=v8',
30.61 gyp info spawn args   '--depth=.',
30.61 gyp info spawn args   '--no-parallel',
30.61 gyp info spawn args   '--generator-output',
30.61 gyp info spawn args   'build',
30.61 gyp info spawn args   '-Goutput_dir=.'
30.61 gyp info spawn args ]
30.61 Traceback (most recent call last):
30.61   File "/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
30.61     sys.exit(gyp.script_main())
30.61              ^^^^^^^^^^^^^^^^^
30.61   File "/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
30.61     return main(sys.argv[1:])
30.61            ^^^^^^^^^^^^^^^^^^
30.61   File "/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
30.61     return gyp_main(args)
30.61            ^^^^^^^^^^^^^^
30.61   File "/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
30.61     [generator, flat_list, targets, data] = Load(
30.61                                             ^^^^^
30.61   File "/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
30.61     result = gyp.input.Load(
30.61              ^^^^^^^^^^^^^^^
30.61   File "/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
30.61     LoadTargetBuildFile(
30.61   File "/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
30.61     build_file_data = LoadOneBuildFile(
30.61                       ^^^^^^^^^^^^^^^^^
30.61   File "/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
30.61     build_file_contents = open(build_file_path, "rU").read()
30.61                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
30.61 ValueError: invalid mode: 'rU' while trying to load binding.gyp
30.61 gyp ERR! configure error
30.61 gyp ERR! stack Error: `gyp` failed with exit code: 1
30.61 gyp ERR! stack     at ChildProcess.onCpExit (/app/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:351:16)
30.61 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
30.61 gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
30.61 gyp ERR! System Linux 6.4.8-orbstack-00059-g106c60a3471f
30.61 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-gyp" "rebuild"
30.61 gyp ERR! cwd /app/node_modules/microtime
30.61 gyp ERR! node -v v18.16.1
30.61 gyp ERR! node-gyp -v v7.1.2
30.61 gyp ERR! not ok
30.61 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install --pure-lockfile" did not complete successfully: exit code: 1
```
Appears to be back on the python dependency side: `ValueError: invalid mode: 'rU' while trying to load binding.gyp`

tbf this is at the top-level `docker-compose up/build` stage. Could stick to just the api package directory and build a one-off `Dockerfile` as that's what I need right now.

**Comment by pythoninthegrass** [comment] 2023-08-15 04:43
Success!

```bash
λ docker build -f packages/api/Dockerfile -t my-omni-api .
[+] Building 18.6s (37/37) FINISHED                                                                     docker:orbstack
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.93kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 156B                                                                                  0.0s
 => [internal] load metadata for docker.io/library/node:18.16-alpine                                               0.0s
 => [internal] load build context                                                                                  0.3s
 => => transferring context: 43.39MB                                                                               0.3s
 => [runner  1/10] FROM docker.io/library/node:18.16-alpine                                                        0.0s
 => CACHED [runner  2/10] WORKDIR /app                                                                             0.0s
 => CACHED [builder  3/24] RUN apk add g++ make python3                                                            0.0s
 => CACHED [builder  4/24] COPY package.json .                                                                     0.0s
 => CACHED [builder  5/24] COPY yarn.lock .                                                                        0.0s
 => CACHED [builder  6/24] COPY tsconfig.json .                                                                    0.0s
 => CACHED [builder  7/24] COPY .prettierrc .                                                                      0.0s
 => CACHED [builder  8/24] COPY .eslintrc .                                                                        0.0s
 => CACHED [builder  9/24] COPY /packages/readabilityjs/package.json ./packages/readabilityjs/package.json         0.0s
 => CACHED [builder 10/24] COPY /packages/api/package.json ./packages/api/package.json                             0.0s
 => CACHED [builder 11/24] COPY /packages/text-to-speech/package.json ./packages/text-to-speech/package.json       0.0s
 => CACHED [builder 12/24] COPY /packages/content-handler/package.json ./packages/content-handler/package.json     0.0s
 => CACHED [builder 13/24] RUN yarn upgrade @npmcli/run-script@6.0.2                                               0.0s
 => CACHED [builder 14/24] RUN yarn install --pure-lockfile                                                        0.0s
 => CACHED [builder 15/24] ADD /packages/readabilityjs ./packages/readabilityjs                                    0.0s
 => CACHED [builder 16/24] ADD /packages/api ./packages/api                                                        0.0s
 => CACHED [builder 17/24] ADD /packages/text-to-speech ./packages/text-to-speech                                  0.0s
 => CACHED [builder 18/24] ADD /packages/content-handler ./packages/content-handler                                0.0s
 => CACHED [builder 19/24] RUN yarn workspace @omnivore/text-to-speech-handler build                               0.0s
 => CACHED [builder 20/24] RUN yarn workspace @omnivore/content-handler build                                      0.0s
 => CACHED [builder 21/24] RUN yarn workspace @omnivore/api build                                                  0.0s
 => CACHED [builder 22/24] RUN rm -rf /app/packages/api/node_modules                                               0.0s
 => CACHED [builder 23/24] RUN rm -rf /app/node_modules                                                            0.0s
 => [builder 24/24] RUN yarn install --pure-lockfile --production                                                  8.1s
 => CACHED [runner  3/10] COPY --from=builder /app/packages/api/dist /app/packages/api/dist                        0.0s
 => CACHED [runner  4/10] COPY --from=builder /app/packages/readabilityjs/ /app/packages/readabilityjs/            0.0s
 => CACHED [runner  5/10] COPY --from=builder /app/packages/api/package.json /app/packages/api/package.json        0.0s
 => CACHED [runner  6/10] COPY --from=builder /app/packages/api/node_modules /app/packages/api/node_modules        0.0s
 => [runner  7/10] COPY --from=builder /app/node_modules /app/node_modules                                         2.4s
 => [runner  8/10] COPY --from=builder /app/package.json /app/package.json                                         0.0s
 => [runner  9/10] COPY --from=builder /app/packages/text-to-speech/ /app/packages/text-to-speech/                 0.0s
 => [runner 10/10] COPY --from=builder /app/packages/content-handler/ /app/packages/content-handler/               0.0s
 => exporting to image                                                                                             3.7s
 => => exporting layers                                                                                            3.7s
 => => writing image sha256:d86ee1bc2c9f85d4448a54d9f658647ae222ba5f1379a4e7bddeaf78ec9ad498                       0.0s
 => => naming to docker.io/library/my-omni-api                                                                     0.0s
```

**Comment by pythoninthegrass** [comment] 2023-08-15 04:51
> to resolve this issue before they fix it, you can modify the Dockerfile. It seems that the problem is caused by a lower version of @npmcli/run-script

Totally missed you changed _three_ separate dockerfiles! That solved it across the board for me. Excellent catch!

**Comment by jacksonh** [comment] 2023-08-15 05:24
Thanks, I have a PR that bumps up that script, unfortunately its part of our build tool so really tough to end to end test everything.

**Comment by LeetaoGoooo** [comment] 2023-08-15 05:40
> Totally missed you changed _three_ separate dockerfiles! That solved it across the board for me. Excellent catch!

 It's great to hear that it solved the issue for you :)

**Comment by LeetaoGoooo** [comment] 2023-08-15 05:42
You're welcome

> Thanks, I have a PR that bumps up that script, unfortunately its part of our build tool so really tough to end to end test everything.

That's perfectly fine! 😄 Once the pull request is merged, we can consider this issue resolved and close it accordingly. If there's anything else I can assist you with, please let me know!

**Comment by Vincentdu-cn** [comment] 2024-02-23 01:33
I have add RUN yarn upgrade @npmcli/run-script@6.0.2 to trhee Dockerfile，and build three images,but web still have error like：
=> ERROR [WEB ] RUN yarn install --pure-lockfile
Then I add RUN yarn upgrade @npmcli/run-script@6.0.2 to web Dockerfile，then I get another Error like ：
=> ERROR [WEB ] RUN yarn upgrade @npmcli/run-script@6.0.2

**Comment by jacksonh** [comment] 2024-02-23 02:41
> I have add RUN yarn upgrade @npmcli/run-script@6.0.2 to trhee Dockerfile，and build three images,but web still have error like： => ERROR [WEB ] RUN yarn install --pure-lockfile Then I add RUN yarn upgrade @npmcli/run-script@6.0.2 to web Dockerfile，then I get another Error like ： => ERROR [WEB ] RUN yarn upgrade @npmcli/run-script@6.0.2

Do you have any more of the error message you can show?

**Comment by Vincentdu-cn** [comment] 2024-02-23 06:50
> > I have add RUN yarn upgrade @npmcli/run-script@6.0.2 to trhee Dockerfile，and build three images,but web still have error like： => ERROR [WEB ] RUN yarn install --pure-lockfile Then I add RUN yarn upgrade @npmcli/run-script@6.0.2 to web Dockerfile，then I get another Error like ： => ERROR [WEB ] RUN yarn upgrade @npmcli/run-script@6.0.2
> 
> Do you have any more of the error message you can show?

I fork to my own repositorie，and modified four Dockerfile files, added RUN yarn upgrade @npmcli/run-script@6.0.2, the image build was successful! But after docker compose was run, clicking the login button redirected to the address http://localhost:4000/api, I have replaced all localhost in the docker-compose.yml file with my IP address. Another problem is that the status of omnivore-migrate is Exited.
`docker logs omnivore-migrate 
ERROR:  database "omnivore" already exists
create omnivore database
CREATE ROLE
created app_user
yarn workspace v1.22.19
yarn run v1.22.19`
`docker logs omnivore-content-fetch 
yarn workspace v1.22.19
yarn run v1.22.19
warning package.json: No license field
$ node build/src/app.js
starting puppeteer browser
no redisURL supplied: cache

/app/packages/content-fetch/build/src/redis_data_source.js:13
            throw 'Error initializing cache redis client';
            ^
Error initializing cache redis client
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.16.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js start
Directory: /app/packages/content-fetch
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.`
``

**Closed** 2024-11-18 10:35 UTC
